stages:
  - test
  - build

test:
  stage: test
  image: golang:latest
  before_script:
    - mkdir -p "$GOPATH/src/assignment-2"
    - ln -svf "$CI_PROJECT_DIR" "$GOPATH/src/$REPO_NAME"
    - cd "$GOPATH/src/$REPO_NAME"
    - echo $firestore | base64 -d > $GOPATH/src/assignment-2/auth.json
  script:
    - go test ./...

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $firestore | base64 -d > ${CI_PROJECT_DIR}/auth.json
    - echo "{\"auths\":{\"registry.local.mathiaswskoglund.com\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "registry.local.mathiaswskoglund.com/assignment-2:latest"
      --force
