stages:
  - test
  - build

test:
  stage: test
  image: golang:latest
  variables:
    REPO_NAME: gitlab.com/mathias_ws/assignment-2
  before_script:
    - mkdir -p "$GOPATH/src/$(dirname $REPO_NAME)"
    - ln -svf "$CI_PROJECT_DIR" "$GOPATH/src/$REPO_NAME"
    - cd "$GOPATH/src/$REPO_NAME"
    - echo $firestore | base64 -d > $GOPATH/src/$REPO_NAME/auth.json
  script:
    - go test ./... -p 1

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $firestore | base64 -d > ${CI_PROJECT_DIR}/auth.json
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n mathiasws:${REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "mathiasws/assignment2:latest"
      --force
